spring:
  application:
    name: gerenciamento-pessoa

  datasource:
    url: jdbc:h2:mem:gerenciamento_pessoas
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2